version: "3.9"
   
services:
  queue:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  api:
    build: si
    ports:
      - "80:80"
      - "1883:1883"
    depends_on:
      - queue
  back:
    build: SI_API
    ports:
      - "81:80"
    depends_on:
      - queue
  gen:
    build: Generator
    depends_on:
      - api