version: "3.9"
   
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
    ports:
      - "27017:27017"
  queue:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
  back:
    environment:
      MONGO_IP: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: user
      MONGO_PASSWORD: pwd
      MONGO_DB_NAME: 175573
      MONGO_COLLECTION: SensorData
    build: SI_API
    ports:
      - "81:80"
    depends_on:
      - queue
      - mongo
  gui:
    build: gui
    environment:
      API_PATH: http://back/api/
      API_EXTERNAL_PATH: http://127.0.0.1:81/api/
    ports:
      - "82:80"
    depends_on:
      - back
  gen:
    environment:
      SI_NUMBER_OF_SENSORS: 30
      SI_DELAY_ON_X: 2
      SI_DELAY_ON_Y: 2
      SI_DELAY_ON_Z: 1
      SI_DELAY_ON_A: 1
      SI_NUMBER_OF_REPETITIONS: -1
      SI_TERMOMETER_MIN: -4000
      SI_TERMOMETER_MAX: 5000
      SI_BAROMETER_MIN: 96000
      SI_BAROMETER_MAX: 106000
      SI_HYGROMETER_MIN: 0
      SI_HYGROMETER_MAX: 10000
      SI_PHOTOMETER_MIN: 2000
      SI_PHOTOMETER_MAX: 11000000
    build: Generator
    depends_on:
      - back
